export default {
  TOGGLE_CART_DROPDOWN : "TOGGLE_CART_DROPDOWN",
  CLOSE_CART_DROPDOWN : "CLOSE_CART_DROPDOWN",
  ADD_PRODUCT_ITEM_TO_CART : "ADD_PRODUCT_ITEM_TO_CART",
  REMOVE_ALERT_CART : "REMOVE_ALERT_CART",
  INCREASE_PRODUCT_QUANTITY : "INCREASE_PRODUCT_QUANTITY",
  DECREASE_PRODUCT_QUANTITY : "DECREASE_PRODUCT_QUANTITY",
  REMOVE_PRODUCT_FROM_CART : "REMOVE_PRODUCT_FROM_CART",
  CLEAR_CART_ITEMS  : "CLEAR_CART_ITEMS"
}