const productActionTypes = {
  FETCH_BEST_SELL_PRODUCTS_START : "FETCH_BEST_SELL_PRODUCTS_START",
  FETCH_BEST_SELL_PRODUCTS_SUCCESS : "FETCH_BEST_SELL_PRODUCTS_SUCCESS",
}

export default productActionTypes