export default {
  GET_CURRENT_USER_START : "GET_CURRENT_USER_START",
  GET_CURRENT_USER_SUCCESS : "GET_CURRENT_USER_SUCCESS",
  GET_CURRENT_USER_FAIL : "GET_CURRENT_USER_FAIL",
  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAIL: "SIGN_UP_FAIL",
  SIGN_IN_START: "SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAIL: "SIGN_IN_FAIL",
  SIGN_OUT_USER_START : "SIGN_OUT_USER_START",
  SIGN_OUT_USER_SUCCESS : "SIGN_OUT_USER_SUCCESS",
  SIGN_OUT_USER_FAIL : "SIGN_OUT_USER_FAIL",
}