export default {
  FETCH_ORDERS_START : "FETCH_ORDERS_START",
  FETCH_ORDERS_SUCCESS : "FETCH_ORDERS_SUCCESS",
  FETCH_ORDERS_FAIL : "FETCH_ORDERS_FAIL",
  ADD_NEW_ORDER_START : "ADD_NEW_ORDER_START",
  ADD_NEW_ORDER_SUCCESS : "ADD_NEW_ORDER_SUCCESS",
  ADD_NEW_ORDER_FAIL : "ADD_NEW_ORDER_FAIL",
  CLEAR_ERROR : "CLEAR_ERROR",
  SET_HAS_MORE_ORDERS : "SET_HAS_MORE_ORDERS"
}